version: "3.6"

services:
  so1:
    image: ${SPLUNK_IMAGE:-splunk/splunk:latest}
    container_name: so1
    environment:
      - SPLUNK_START_ARGS=--accept-license
      - SPLUNK_PASSWORD=${SPLUNK_PASS}
    volumes:
      - ./app:/opt/splunk/etc/apps/eve-online-monitor
    ports:
      - 8000:8000
